import 'product.dart';

final List<Product> sampleProducts = [
  Product(
    id: '1',
    name: 'Smartphone XYZ',
    description: 'El último smartphone con las mejores características del mercado.',
    price: 699.99,
    imageUrl: 'https://example.com/phone.jpg',
    category: 'Electrónicos',
    rating: 4.5,
    stock: 50,
    images: [
      'https://example.com/phone1.jpg',
      'https://example.com/phone2.jpg',
      'https://example.com/phone3.jpg',
    ],
    specifications: {
      'pantalla': '6.5 pulgadas',
      'procesador': 'Snapdragon 888',
      'ram': '8GB',
      'almacenamiento': '128GB',
    },
  ),
  Product(
    id: '2',
    name: 'Laptop Pro',
    description: 'Potente laptop para profesionales y gamers.',
    price: 1299.99,
    imageUrl: 'https://example.com/laptop.jpg',
    category: 'Electrónicos',
    rating: 4.8,
    stock: 30,
    images: [
      'https://example.com/laptop1.jpg',
      'https://example.com/laptop2.jpg',
    ],
    specifications: {
      'pantalla': '15.6 pulgadas',
      'procesador': 'Intel i7',
      'ram': '16GB',
      'almacenamiento': '512GB SSD',
    },
  ),
  Product(
    id: '3',
    name: 'Camiseta Casual',
    description: 'Camiseta 100% algodón, cómoda y elegante.',
    price: 29.99,
    imageUrl: 'https://example.com/tshirt.jpg',
    category: 'Ropa',
    rating: 4.2,
    stock: 100,
    images: [
      'https://example.com/tshirt1.jpg',
      'https://example.com/tshirt2.jpg',
    ],
    specifications: {
      'material': 'Algodón',
      'tallas': ['S', 'M', 'L', 'XL'],
      'colores': ['Negro', 'Blanco', 'Azul'],
    },
  ),
  Product(
    id: '4',
    name: 'Zapatillas Deportivas',
    description: 'Zapatillas ideales para running y entrenamiento.',
    price: 89.99,
    imageUrl: 'https://example.com/shoes.jpg',
    category: 'Deportes',
    rating: 4.6,
    stock: 75,
    images: [
      'https://example.com/shoes1.jpg',
      'https://example.com/shoes2.jpg',
    ],
    specifications: {
      'material': 'Malla transpirable',
      'tallas': ['38', '39', '40', '41', '42', '43'],
      'colores': ['Negro', 'Blanco', 'Rojo'],
    },
  ),
  Product(
    id: '5',
    name: 'Sofá Moderno',
    description: 'Sofá elegante y cómodo para tu sala de estar.',
    price: 599.99,
    imageUrl: 'https://example.com/sofa.jpg',
    category: 'Hogar',
    rating: 4.7,
    stock: 20,
    images: [
      'https://example.com/sofa1.jpg',
      'https://example.com/sofa2.jpg',
    ],
    specifications: {
      'material': 'Tela sintética',
      'dimensiones': '200x90x85 cm',
      'colores': ['Gris', 'Beige', 'Azul'],
    },
  ),
  Product(
    id: '6',
    name: 'Smart TV 4K',
    description: 'Televisor inteligente con resolución 4K y HDR.',
    price: 799.99,
    imageUrl: 'https://example.com/tv.jpg',
    category: 'Electrónicos',
    rating: 4.9,
    stock: 25,
    images: [
      'https://example.com/tv1.jpg',
      'https://example.com/tv2.jpg',
    ],
    specifications: {
      'pantalla': '55 pulgadas',
      'resolución': '4K UHD',
      'hdr': 'Sí',
      'smart_tv': 'Sí',
    },
  ),
]; 