// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSQVD8TcUbS0B7cAM4_KImJeBxRx4gZag',
    appId: '1:875292662938:web:b900ce48b7c5665edcd323',
    messagingSenderId: '875292662938',
    projectId: 'ticket-app-62497',
    authDomain: 'ticket-app-62497.firebaseapp.com',
    storageBucket: 'ticket-app-62497.firebasestorage.app',
    measurementId: 'G-NT2XWRCRDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLSkOmtMZdsmsRkBSf_pCh8TGl8b9Tt3U',
    appId: '1:875292662938:android:cb31af20b139937fdcd323',
    messagingSenderId: '875292662938',
    projectId: 'ticket-app-62497',
    storageBucket: 'ticket-app-62497.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBLebp6XKB2fobbGE52ccm3j1iVEwp7nQ',
    appId: '1:875292662938:ios:f77424da520e4d2ddcd323',
    messagingSenderId: '875292662938',
    projectId: 'ticket-app-62497',
    storageBucket: 'ticket-app-62497.firebasestorage.app',
    iosBundleId: 'com.example.ticketApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBLebp6XKB2fobbGE52ccm3j1iVEwp7nQ',
    appId: '1:875292662938:ios:f77424da520e4d2ddcd323',
    messagingSenderId: '875292662938',
    projectId: 'ticket-app-62497',
    storageBucket: 'ticket-app-62497.firebasestorage.app',
    iosBundleId: 'com.example.ticketApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSQVD8TcUbS0B7cAM4_KImJeBxRx4gZag',
    appId: '1:875292662938:web:1b078526131bade3dcd323',
    messagingSenderId: '875292662938',
    projectId: 'ticket-app-62497',
    authDomain: 'ticket-app-62497.firebaseapp.com',
    storageBucket: 'ticket-app-62497.firebasestorage.app',
    measurementId: 'G-R996KP8P6T',
  );

}